package com.codenotfound.webService.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-12-14T17:28:12.710+08:00
 * Generated source version: 3.4.1
 *
 */
@WebServiceClient(name = "testWebService",
                  wsdlLocation = "file:/E:/XXL/WorkSpace/JAVA/GitHub/grpc-java/grpc-java-hello-world/src/main/java/com/codenotfound/webService/client/test.wsdl",
                  targetNamespace = "http://impl.webService.codenotfound.com/")
public class TestWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.codenotfound.com/", "testWebService");
    public final static QName TestWebServiceImplPort = new QName("http://impl.webService.codenotfound.com/", "TestWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/XXL/WorkSpace/JAVA/GitHub/grpc-java/grpc-java-hello-world/src/main/java/com/codenotfound/webService/client/test.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/E:/XXL/WorkSpace/JAVA/GitHub/grpc-java/grpc-java-hello-world/src/main/java/com/codenotfound/webService/client/test.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestWebService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestWebService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort() {
        return super.getPort(TestWebServiceImplPort, TestWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TestWebServiceImplPort, TestWebService.class, features);
    }

}
